name:                tolstoy
version:             0.0.1
github:              "githubuser/tolstoy"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/tolstoy#readme>

dependencies:
  - QuickCheck
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - deepseq
  - exceptions
  - generic-lens
  - lens
  - mtl
  - postgresql-query
  - postgresql-simple
  - quickcheck-instances
  - resource-pool
  - scientific
  - text
  - time
  - transformers
  - type-fun >= 0.1.2
  - uuid-types
  - vector
  - vinyl

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NumDecimals
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

ghc-options:
  - -Wall
ghc-prof-options:
  - -fprof-auto

library:
  source-dirs: src

tests:
  tolstoy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

    dependencies:
      - generic-arbitrary
      - hspec-expectations
      - monad-logger
      - deepseq
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
      - tolstoy

    build-tools:
      - autoexporter
